/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uas.modules.home;

import com.uas.model.Toko;
import com.uas.model.Transaksi;
import com.uas.model.User;
import com.uas.repository.TokoRepository;
import com.uas.repository.TransaksiRepository;
import com.uas.repository.UserRepository;
import com.uas.repository.impl.TokoRepositoryImpl;
import com.uas.repository.impl.TransaksiRepositoryimpl;
import com.uas.repository.impl.UserRepositoryImpl;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 * @author seior
 */
public class HomeAdmin extends javax.swing.JFrame {

    private final TransaksiRepository transaksiRepository;
    private final UserRepository userRepository;
    private final TokoRepository tokoRepository;
    private DefaultTableModel transaksiTableModel;
    private DefaultTableModel userTableModel;
    private DefaultTableModel tokoTableModel;

    /**
     * Creates new form HomeAdmin
     */
    public HomeAdmin(String name) {
        this.transaksiRepository = new TransaksiRepositoryimpl();
        this.userRepository = new UserRepositoryImpl();
        this.tokoRepository = new TokoRepositoryImpl();

        initComponents();

        this.welcomeLabel.setText(welcomeLabel.getText() + name);

        showTables();
        showDataTables();
    }

    public void showTables() {
        Object[] transaksiTableName = {
                "id",
                "id laptop",
                "jasa pengiriman",
                "alamat",
                "pembayaran",
                "total bayar",
                "username"
        };

        Object[] userTableName = {
                "username",
                "password",
                "nama",
                "alamat",
                "no telepon",
                "jenis kelamin",
                "role"
        };

        Object[] tokoTableName = {
                "username",
                "password",
                "nama toko",
                "alamat",
                "rating"
        };

        transaksiTableModel = new DefaultTableModel(null, transaksiTableName);
        userTableModel = new DefaultTableModel(null, userTableName);
        tokoTableModel = new DefaultTableModel(null, tokoTableName);

        this.orderTable.setModel(transaksiTableModel);
        this.userTable.setModel(userTableModel);
        this.tokoTable.setModel(tokoTableModel);
    }

    public void showDataTables() {
        // tabel transaksi
        transaksiTableModel.getDataVector().removeAllElements();
        transaksiTableModel.fireTableDataChanged();

        List<Transaksi> transaksis = transaksiRepository.findAll();

        transaksis.forEach(transaksi -> {
            Object[] data = {
                    transaksi.getId(),
                    transaksi.getIdLaptop(),
                    transaksi.getJasaPengiriman(),
                    transaksi.getAlamat(),
                    transaksi.getPembayaran(),
                    transaksi.getTotalBayar(),
                    transaksi.getUsername()
            };

            transaksiTableModel.addRow(data);
        });

        // tabel user
        userTableModel.getDataVector().removeAllElements();
        userTableModel.fireTableDataChanged();

        List<User> users = userRepository.findAll();

        users.forEach(user -> {
            Object[] data = {
                    user.getUsername(),
                    user.getPassword(),
                    user.getNama(),
                    user.getAlamat(),
                    user.getNoTelp(),
                    user.getJk(),
                    user.getRole()
            };

            userTableModel.addRow(data);
        });

        // tabel toko
        tokoTableModel.getDataVector().removeAllElements();
        tokoTableModel.fireTableDataChanged();

        List<Toko> tokos = tokoRepository.findAll();

        tokos.forEach(toko -> {
            Object[] data = {
                    toko.getUsername(),
                    toko.getPassword(),
                    toko.getNamaToko(),
                    toko.getAlamat(),
                    toko.getRating()
            };

            tokoTableModel.addRow(data);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tokoTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dashboard"));

        userTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(userTable);

        tokoTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane2.setViewportView(tokoTable);

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane3.setViewportView(orderTable);

        jButton1.setText("Tentang");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        welcomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        welcomeLabel.setText("Selamat Datang, ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(logoutButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(welcomeLabel))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(welcomeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(logoutButton))
                                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int tentang = JOptionPane.showOptionDialog(
                this,
                "Aplikasi ini dibuat untuk menyelesaikan tugas UAS PBO",
                "Tentang",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, null, null
        );

        if (tentang == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Nama Kelompok : \n" +
                            "- Raden Mohamad Rishwan\n" +
                            "- Radika Tripena Lubis\n" +
                            "- Raihan Akbar Saputro\n" +
                            "- Rangga Fitra",
                    "Kelompok",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTable orderTable;
    private javax.swing.JTable tokoTable;
    private javax.swing.JTable userTable;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
