/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uas.modules.home;

import com.uas.modules.belilaptop.BeliLaptop;
import com.uas.modules.login.Login;
import com.uas.modules.transaksi.LihatTransaksi;

/**
 * @author seior
 */
public class HomeUser extends javax.swing.JFrame {

    private String username;

    /**
     * Creates new form HomeUser
     */
    public HomeUser(String name, String username) {
        initComponents();

        this.username = username;
        welcomeLabel.setText(welcomeLabel.getText() + name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        keluarBTN = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        beliBTN = new javax.swing.JButton();
        transaksiBTN = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        logoutBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        keluarBTN.setBorder(javax.swing.BorderFactory.createTitledBorder("Home"));

        welcomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        welcomeLabel.setText("Selamat Datang, ");

        beliBTN.setText("Beli Laptop");
        beliBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliBTNActionPerformed(evt);
            }
        });

        transaksiBTN.setText("Lihat Transaksi");
        transaksiBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiBTNActionPerformed(evt);
            }
        });

        jButton4.setText("Keluar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        logoutBTN.setText("Logout");
        logoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout keluarBTNLayout = new javax.swing.GroupLayout(keluarBTN);
        keluarBTN.setLayout(keluarBTNLayout);
        keluarBTNLayout.setHorizontalGroup(
            keluarBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keluarBTNLayout.createSequentialGroup()
                .addGroup(keluarBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(keluarBTNLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(welcomeLabel))
                    .addGroup(keluarBTNLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(keluarBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transaksiBTN)
                            .addComponent(beliBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        keluarBTNLayout.setVerticalGroup(
            keluarBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keluarBTNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel)
                .addGap(37, 37, 37)
                .addComponent(beliBTN)
                .addGap(18, 18, 18)
                .addComponent(transaksiBTN)
                .addGap(18, 18, 18)
                .addComponent(logoutBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(keluarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(keluarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTNActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBTNActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void beliBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliBTNActionPerformed
        new BeliLaptop(this.username).setVisible(true);
    }//GEN-LAST:event_beliBTNActionPerformed

    private void transaksiBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiBTNActionPerformed
       new LihatTransaksi(this.username).setVisible(true);
    }//GEN-LAST:event_transaksiBTNActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beliBTN;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel keluarBTN;
    private javax.swing.JButton logoutBTN;
    private javax.swing.JButton transaksiBTN;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
