/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uas.modules.home;

import com.uas.model.Laptop;
import com.uas.modules.login.Login;
import com.uas.repository.LaptopRepository;
import com.uas.repository.impl.LaptopRepositoryImpl;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 * @author seior
 */
public class HomeToko extends javax.swing.JFrame {

    private final String username;
    private String selectedId;
    private final LaptopRepository laptopRepository;
    private DefaultTableModel tableModel;

    /**
     * Creates new form HomeToko
     */
    public HomeToko(String username) {
        this.laptopRepository = new LaptopRepositoryImpl();
        this.username = username;

        this.setLocationRelativeTo(null);
        initComponents();

        showTable();
        showDataTable();

        this.updateBTN.setEnabled(false);
    }

    public void showTable() {
        Object[] tableName = {
                "id", "harga", "nama", "terjual", "kondisi", "tipe", "deskripsi"
        };

        tableModel = new DefaultTableModel(null, tableName);

        laptopTabel.setModel(tableModel);
    }

    public void showDataTable() {
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();

        List<Laptop> result = laptopRepository.findAll(username);

        result.forEach(laptop -> {
            Object[] data = {
                    laptop.getId(),
                    laptop.getHarga(),
                    laptop.getNama(),
                    laptop.getTerjual(),
                    laptop.getKondisi(),
                    laptop.getTipe(),
                    laptop.getDeskripsi()
            };

            tableModel.addRow(data);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        namaTF = new javax.swing.JTextField();
        hargaTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tipeTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        kondisiCB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        deskripsiTA = new javax.swing.JTextArea();
        tambahBTN = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        laptopTabel = new javax.swing.JTable();
        keluarBTN = new javax.swing.JButton();
        logoutBTN = new javax.swing.JButton();
        hapusBTN = new javax.swing.JButton();
        updateBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Home"));

        jLabel1.setText("Nama");

        jLabel2.setText("Harga");

        jLabel3.setText("Kondisi");

        jLabel4.setText("Tipe");

        jLabel5.setText("Deskripsi");

        kondisiCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baru", "Bekas" }));

        deskripsiTA.setColumns(20);
        deskripsiTA.setRows(5);
        jScrollPane1.setViewportView(deskripsiTA);

        tambahBTN.setText("Tambah");
        tambahBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBTNActionPerformed(evt);
            }
        });

        laptopTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        laptopTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laptopTabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(laptopTabel);

        keluarBTN.setText("Keluar");
        keluarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarBTNActionPerformed(evt);
            }
        });

        logoutBTN.setText("Logout");
        logoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTNActionPerformed(evt);
            }
        });

        hapusBTN.setText("Hapus");
        hapusBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBTNActionPerformed(evt);
            }
        });

        updateBTN.setText("Update");
        updateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keluarBTN)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(namaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hargaTF)
                            .addComponent(kondisiCB, 0, 298, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tambahBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(updateBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hapusBTN)
                                .addGap(54, 54, 54))
                            .addComponent(tipeTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(namaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(hargaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(kondisiCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tipeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tambahBTN)
                            .addComponent(updateBTN)
                            .addComponent(hapusBTN))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keluarBTN)
                    .addComponent(logoutBTN))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBTNActionPerformed
        Laptop laptop = new Laptop();

        laptop.setNama(namaTF.getText());
        laptop.setHarga(hargaTF.getText());
        laptop.setKondisi(kondisiCB.getSelectedItem().toString());
        laptop.setTipe(tipeTF.getText());
        laptop.setDeskripsi(deskripsiTA.getText());
        laptop.setUsername(username);

        laptopRepository.save(laptop);

        JOptionPane.showMessageDialog(null, "data berhasil disimpan");
        showDataTable();
    }//GEN-LAST:event_tambahBTNActionPerformed

    private void updateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTNActionPerformed
        Laptop laptop = new Laptop();

        laptop.setId(selectedId);
        laptop.setNama(namaTF.getText());
        laptop.setHarga(hargaTF.getText());
        laptop.setKondisi(kondisiCB.getSelectedItem().toString());
        laptop.setTipe(tipeTF.getText());
        laptop.setDeskripsi(deskripsiTA.getText());
        laptop.setUsername(username);

        laptopRepository.update(laptop);

        JOptionPane.showMessageDialog(null, "data berhasil diupdate");
        showDataTable();

        updateBTN.setEnabled(false);
    }//GEN-LAST:event_updateBTNActionPerformed

    private void laptopTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laptopTabelMouseClicked
        namaTF.setText(laptopTabel.getValueAt(laptopTabel.getSelectedRow(), 1).toString());
        hargaTF.setText(laptopTabel.getValueAt(laptopTabel.getSelectedRow(), 2).toString());
        tipeTF.setText(laptopTabel.getValueAt(laptopTabel.getSelectedRow(), 5).toString());

        kondisiCB.setSelectedItem(laptopTabel.getValueAt(laptopTabel.getSelectedRow(), 4).toString());
        deskripsiTA.setText(laptopTabel.getValueAt(laptopTabel.getSelectedRow(), 6).toString());
        selectedId = laptopTabel.getValueAt(laptopTabel.getSelectedRow(), 0).toString();

        updateBTN.setEnabled(true);
    }//GEN-LAST:event_laptopTabelMouseClicked

    private void hapusBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBTNActionPerformed
        laptopRepository.deleteById(selectedId);
        showDataTable();
        JOptionPane.showMessageDialog(null, "data berhasil di hapus");
    }//GEN-LAST:event_hapusBTNActionPerformed

    private void logoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTNActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBTNActionPerformed

    private void keluarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarBTNActionPerformed
        this.dispose();
    }//GEN-LAST:event_keluarBTNActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea deskripsiTA;
    private javax.swing.JButton hapusBTN;
    private javax.swing.JTextField hargaTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton keluarBTN;
    private javax.swing.JComboBox<String> kondisiCB;
    private javax.swing.JTable laptopTabel;
    private javax.swing.JButton logoutBTN;
    private javax.swing.JTextField namaTF;
    private javax.swing.JButton tambahBTN;
    private javax.swing.JTextField tipeTF;
    private javax.swing.JButton updateBTN;
    // End of variables declaration//GEN-END:variables
}
