/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uas.modules.transaksi;

import com.uas.model.StatusPemesanan;
import com.uas.model.Transaksi;
import com.uas.repository.StatusPemesananRepository;
import com.uas.repository.TransaksiRepository;
import com.uas.repository.impl.StatusPemesananRepositoryImpl;
import com.uas.repository.impl.TransaksiRepositoryimpl;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 * @author seior
 */
public class LihatTransaksi extends javax.swing.JFrame {

    private final String username;
    private final TransaksiRepository transaksiRepository;
    private final StatusPemesananRepository statusPemesananRepository;
    private DefaultTableModel tableModel;

    /**
     * Creates new form LihatTransaksi
     */
    public LihatTransaksi(String username) {
        this.username = username;
        this.statusPemesananRepository = new StatusPemesananRepositoryImpl();
        this.transaksiRepository = new TransaksiRepositoryimpl();
        initComponents();

        showStatus(false);

        showTables();
        showDataTables();
    }

    public void showStatus(Boolean status) {
        this.idTransaksiLabel.setVisible(status);
        this.statusPembayaranLabel.setVisible(status);
        this.statusPemesananLabel.setVisible(status);

        this.barangBTN.setVisible(status);
        this.statusBTN.setVisible(status);

    }

    public void showTables() {
        Object[] tableNames = {
                "id",
                "id laptop",
                "jasa pengiriman",
                "alamat",
                "pembayaran",
                "total bayar",
        };

        tableModel = new DefaultTableModel(null, tableNames);

        transaksiTable.setModel(tableModel);
    }

    public void showDataTables() {
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();

        List<Transaksi> result = transaksiRepository.findAll(this.username);

        result.forEach(transaksi -> {
            Object[] data = {
                    transaksi.getId(),
                    transaksi.getIdLaptop(),
                    transaksi.getJasaPengiriman(),
                    transaksi.getAlamat(),
                    transaksi.getPembayaran(),
                    transaksi.getTotalBayar()
            };

            tableModel.addRow(data);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transaksiTable = new javax.swing.JTable();
        statusBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        kurisLabel = new javax.swing.JLabel();
        metodeLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        barangBTN = new javax.swing.JButton();
        statusPembayaranLabel = new javax.swing.JLabel();
        idTransaksiLabel = new javax.swing.JLabel();
        statusPemesananLabel = new javax.swing.JLabel();
        kembaliBTN = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("List Transaksi"));

        jLabel1.setText("Semua Transaksi Saya");

        transaksiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        transaksiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(transaksiTable);

        statusBTN.setText("Lihat status pemesanan");

        jLabel2.setText("Id Transaksi");

        jLabel3.setText("Jasa Pengiriman");

        jLabel4.setText("Metode Pembayaran");

        jLabel5.setText("Total Bayar");

        jLabel6.setText("Alamat");

        namaLabel.setText("Kosong");

        kurisLabel.setText("Kosong");

        metodeLabel.setText("Kosong");

        totalLabel.setText("Kosong");

        alamatLabel.setText("Kosong");
        alamatLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel7.setText("ID Transaksi");

        jLabel8.setText("Status Pembayaran");

        barangBTN.setText("Barang Diterima");
        barangBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangBTNActionPerformed(evt);
            }
        });

        statusPembayaranLabel.setText("Kosong");

        idTransaksiLabel.setText("Kosong");

        statusPemesananLabel.setText("Kosong");

        kembaliBTN.setText("Kembali");
        kembaliBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliBTNActionPerformed(evt);
            }
        });

        jLabel10.setText("Status Pemesanan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(69, 69, 69)
                                .addComponent(namaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alamatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                    .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                    .addComponent(metodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                    .addComponent(kurisLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(kembaliBTN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(barangBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusBTN))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idTransaksiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusPembayaranLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusPemesananLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(namaLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(kurisLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(metodeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(totalLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(alamatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusBTN)
                    .addComponent(jLabel7)
                    .addComponent(idTransaksiLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(statusPembayaranLabel)
                    .addComponent(barangBTN))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(statusPemesananLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kembaliBTN)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliBTNActionPerformed
        this.dispose();
    }//GEN-LAST:event_kembaliBTNActionPerformed

    private void transaksiTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiTableMouseClicked
        showStatus(true);

        // set label transaksi
        this.namaLabel.setText(getValueFromTable(1));
        this.kurisLabel.setText(getValueFromTable(2));
        this.metodeLabel.setText(getValueFromTable(4));
        this.totalLabel.setText(getValueFromTable(5));
        this.alamatLabel.setText(getValueFromTable(3));

        StatusPemesanan pemesanan = this.statusPemesananRepository.findByIdTransaksi(getValueFromTable(0));

        // set label status pemesanan
        idTransaksiLabel.setText(pemesanan.getIdTransaksi());
        statusPembayaranLabel.setText(pemesanan.getStatusPembayaran());
        statusPemesananLabel.setText(pemesanan.getStatusPemesanan());

        if (statusPemesananLabel.getText().equals("Belum diproses")) {
            barangBTN.setEnabled(false);
        } else {
            barangBTN.setEnabled(true);
        }

    }//GEN-LAST:event_transaksiTableMouseClicked

    private void barangBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangBTNActionPerformed
        statusPemesananRepository.delete(getValueFromTable(0));
        transaksiRepository.delete(Integer.parseInt(getValueFromTable(0)));

        JOptionPane.showMessageDialog(null, "Barang telah sampai!!!, data akan dihapus dari transaksi.");
        showDataTables();
        showStatus(false);
    }//GEN-LAST:event_barangBTNActionPerformed

    private String getValueFromTable(int column) {
        return transaksiTable.getValueAt(transaksiTable.getSelectedRow(), column).toString();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JButton barangBTN;
    private javax.swing.JLabel idTransaksiLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembaliBTN;
    private javax.swing.JLabel kurisLabel;
    private javax.swing.JLabel metodeLabel;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JButton statusBTN;
    private javax.swing.JLabel statusPembayaranLabel;
    private javax.swing.JLabel statusPemesananLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTable transaksiTable;
    // End of variables declaration//GEN-END:variables
}
