/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uas.modules.login;

import com.uas.exception.NotFoundException;
import com.uas.model.Toko;
import com.uas.model.User;
import com.uas.modules.home.HomeAdmin;
import com.uas.modules.home.HomeUser;
import com.uas.repository.TokoRepository;
import com.uas.repository.UserRepository;
import com.uas.repository.impl.TokoRepositoryImpl;
import com.uas.modules.home.HomeToko;
import com.uas.modules.register.Register;
import com.uas.repository.impl.UserRepositoryImpl;

import javax.swing.*;

/**
 * @author seior
 */
public class Login extends javax.swing.JFrame {

    private String loginAs;
    private final TokoRepository tokoRepository;
    private final UserRepository userRepository;

    /**
     * Creates new form Login
     */
    public Login() {
        this.tokoRepository = new TokoRepositoryImpl();
        this.userRepository = new UserRepositoryImpl();


        initComponents();

        usernameTF.setVisible(false);
        passwordTF.setVisible(false);
        usernameLabel.setVisible(false);
        passwordLabel.setVisible(false);
        loginBTN.setVisible(false);
    }

    public void showLoginComponent(String loginAs) {
        usernameTF.setVisible(true);
        passwordTF.setVisible(true);
        usernameLabel.setVisible(true);
        passwordLabel.setVisible(true);
        loginBTN.setVisible(true);

        this.loginAs = loginAs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        loginPembeliBTN = new javax.swing.JButton();
        loginPenjualBTN = new javax.swing.JButton();
        usernameTF = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordTF = new javax.swing.JPasswordField();
        loginBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        registerPembeliBTN = new javax.swing.JButton();
        registerPenjualBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Silahkan Login Terlebih Dahulu");

        loginPembeliBTN.setText("Login Sebagai Pembeli");
        loginPembeliBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPembeliBTNActionPerformed(evt);
            }
        });

        loginPenjualBTN.setText("Login Sebagai Penjual");
        loginPenjualBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPenjualBTNActionPerformed(evt);
            }
        });

        usernameLabel.setText("Username");

        passwordLabel.setText("Password");

        loginBTN.setText("Login");
        loginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTNActionPerformed(evt);
            }
        });

        jLabel4.setText("atau daftar disini");

        registerPembeliBTN.setText("Daftar sebagai Pembeli");
        registerPembeliBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPembeliBTNActionPerformed(evt);
            }
        });

        registerPenjualBTN.setText("Daftar sebagai Penjual");
        registerPenjualBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPenjualBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 205, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(loginPembeliBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(loginPenjualBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(210, 210, 210))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(loginBTN)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(usernameLabel)
                                                                .addComponent(passwordLabel))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(usernameTF)
                                                                .addComponent(passwordTF, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)))
                                                .addComponent(registerPembeliBTN)
                                                .addComponent(registerPenjualBTN)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(32, 32, 32)
                                .addComponent(loginPembeliBTN)
                                .addGap(27, 27, 27)
                                .addComponent(loginPenjualBTN)
                                .addGap(97, 97, 97)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(usernameLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordLabel)
                                        .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(loginBTN)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(registerPembeliBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(registerPenjualBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginPenjualBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPenjualBTNActionPerformed
        showLoginComponent("penjual");
    }//GEN-LAST:event_loginPenjualBTNActionPerformed

    private void registerPembeliBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPembeliBTNActionPerformed
        new Register("pembeli").setVisible(true);
    }//GEN-LAST:event_registerPembeliBTNActionPerformed

    private void registerPenjualBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPenjualBTNActionPerformed
        new Register("penjual").setVisible(true);
    }//GEN-LAST:event_registerPenjualBTNActionPerformed

    private void loginPembeliBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPembeliBTNActionPerformed
        showLoginComponent("pembeli");
    }//GEN-LAST:event_loginPembeliBTNActionPerformed

    private void loginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTNActionPerformed
        if (loginAs.equals("penjual")) {
            Toko toko = new Toko();

            toko.setUsername(usernameTF.getText());
            toko.setPassword(String.valueOf(passwordTF.getPassword()));

            if (this.tokoRepository.login(toko)) {
                new HomeToko(toko.getUsername()).setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Username atau Password Salah");
            }
        } else if (loginAs.equals("pembeli")) {
            User user = new User();

            user.setUsername(usernameTF.getText());
            user.setPassword(String.valueOf(passwordTF.getPassword()));


            if (this.userRepository.login(user)) {
                try {
                    User newUser = userRepository.findByUsername(user.getUsername());

                    if (newUser.getRole().equals("admin")) {
                        new HomeAdmin(newUser.getNama()).setVisible(true);
                    } else {
                    HomeUser homeUser = new HomeUser(newUser.getNama(), newUser.getUsername());
                        homeUser.setVisible(true);
                    }

                    this.dispose();
                } catch (NotFoundException e) {
                    JOptionPane.showMessageDialog(null, "Username atau Password Salah");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Username atau Password Salah");
            }
        }
    }//GEN-LAST:event_loginBTNActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBTN;
    private javax.swing.JButton loginPembeliBTN;
    private javax.swing.JButton loginPenjualBTN;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JButton registerPembeliBTN;
    private javax.swing.JButton registerPenjualBTN;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
