/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uas.modules.belilaptop;

import com.uas.model.LaptopToko;
import com.uas.repository.LaptopRepository;
import com.uas.repository.impl.LaptopRepositoryImpl;

import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 * @author seior
 */
public class BeliLaptop extends javax.swing.JFrame {

    private LaptopRepository laptopRepository;
    private DefaultTableModel tableModel;
    private String username;

    /**
     * Creates new form BeliLaptop
     */
    public BeliLaptop(String username) {
        this.username = username;
        this.laptopRepository = new LaptopRepositoryImpl();

        initComponents();

        showTable();
        showDataTable();
    }

    public void showTable() {
        Object[] tableName = {
                "id", "username", "harga", "nama", "terjual", "kondisi", "tipe", "deskripsi", "toko"
        };

        tableModel = new DefaultTableModel(null, tableName);

        laptopTabel.setModel(tableModel);
    }

    public void showDataTable() {
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();

        List<LaptopToko> result = laptopRepository.findAllToko();

        result.forEach(laptop -> {
            Object[] data = {
                    laptop.getId(),
                    laptop.getUsername(),
                    laptop.getHarga(),
                    laptop.getNama(),
                    laptop.getTerjual(),
                    laptop.getKondisi(),
                    laptop.getTipe(),
                    laptop.getDeskripsi(),
                    laptop.getNamaToko()
            };

            tableModel.addRow(data);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        hargaLabel = new javax.swing.JLabel();
        kondisiLabel = new javax.swing.JLabel();
        tipeLabel = new javax.swing.JLabel();
        deskripsiLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        laptopTabel = new javax.swing.JTable();
        beliBTN = new javax.swing.JButton();
        kembaliBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Beli Laptop"));

        jLabel1.setText("Nama");

        jLabel2.setText("Harga");

        jLabel3.setText("Kondisi");

        jLabel4.setText("Tipe");

        jLabel5.setText("Deskripsi");

        namaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        namaLabel.setText("kosong");

        hargaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hargaLabel.setText("kosong");

        kondisiLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        kondisiLabel.setText("kosong");

        tipeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tipeLabel.setText("kosong");

        deskripsiLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        deskripsiLabel.setText("kosong");

        laptopTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        laptopTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laptopTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(laptopTabel);

        beliBTN.setText("Beli");
        beliBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliBTNActionPerformed(evt);
            }
        });

        kembaliBTN.setText("Kembali");
        kembaliBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deskripsiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(tipeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kondisiLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hargaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(beliBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kembaliBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(namaLabel))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(hargaLabel))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kondisiLabel))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tipeLabel))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(deskripsiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beliBTN)
                    .addComponent(kembaliBTN))
                .addGap(0, 124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliBTNActionPerformed
        this.dispose();
    }//GEN-LAST:event_kembaliBTNActionPerformed

    private void laptopTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laptopTabelMouseClicked
        namaLabel.setText(laptopTabel.getValueAt(laptopTabel.getSelectedRow(), 3).toString());
        hargaLabel.setText(laptopTabel.getValueAt(laptopTabel.getSelectedRow(), 2).toString());
        kondisiLabel.setText(laptopTabel.getValueAt(laptopTabel.getSelectedRow(), 5).toString());
        tipeLabel.setText(laptopTabel.getValueAt(laptopTabel.getSelectedRow(), 6).toString());
        deskripsiLabel.setText(laptopTabel.getValueAt(laptopTabel.getSelectedRow(), 7).toString());
    }//GEN-LAST:event_laptopTabelMouseClicked

    private void beliBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliBTNActionPerformed
        LaptopToko laptopToko = new LaptopToko();

        laptopToko.setId(laptopTabel.getValueAt(laptopTabel.getSelectedRow(), 0).toString());
        laptopToko.setHarga(hargaLabel.getText());
        laptopToko.setUsername(this.username);
        
        new TransaksiBaru(laptopToko).setVisible(true);
    }//GEN-LAST:event_beliBTNActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beliBTN;
    private javax.swing.JLabel deskripsiLabel;
    private javax.swing.JLabel hargaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembaliBTN;
    private javax.swing.JLabel kondisiLabel;
    private javax.swing.JTable laptopTabel;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel tipeLabel;
    // End of variables declaration//GEN-END:variables
}
